### PR TITLE
Added support for Expl

### PR DESCRIPTION
**Pull request by madhavpcm**
Todo
- [ ] Color user defined data types

### CODE REVIEW

**Comment by madhavpcm** [comment]
I did change master to main on my fork. Im not sure how to do this on the main repo, maybe you can change default branch in settings ?

**Comment by itsfarseen** [comment]
Could you also `git rebase --interactive` the PR to have these 3 commits:
* Update repo path in readme
* Fix spl string
* add expl code & screenshot

Pls add explanation for spl string fix in the commit msg.

**Comment by itsfarseen** [comment]
> I did change master to main on my fork. Im not sure how to do this on the main repo, maybe you can change default branch in settings ?

Okay. I'll check.

**Comment by madhavpcm** [comment]
> Could you also git rebase --interactive the PR to have these 3 commits:

I am on the main branch, and my fork is upto date with upstream

> * Update repo path in readme
> * add expl code & screenshot

I did this, changed happcoder97 to itsfarseen, did you mean to edit the commit message ?

> * Fix spl string
I will add explanation sson

**Comment by itsfarseen** [comment]
>  did you mean to edit the commit message 

Yes

I meant, do rebase to rename/squash the commits so that they are nicer to read and feel organized.

**Comment by madhavpcm** [comment]
> > did you mean to edit the commit message
> 
> Yes
> 
> I meant, do rebase to rename/squash the commits so that they are nicer to read and feel organized.

Done

**Pull request merged**
